### PR TITLE
Refactor and `reactive-config` prop feature 

### PR DESCRIPTION
**Pull request by gavin-lb**
# Made the following changes: 
+ Fixed config merging (now does a deep merge/copy and returns a new object instead of mutating arguments)
+ If movable.events.after is supplied in config, patch changeTurn to run before it rather than replace it entirely
+ Added setConfig method to the API
+ Overall refactor to combine redundant operations and move logic away from Vue component
+ Cleaned up PromotionDialog to be less convoluted
+ Fixed old tests for new internal API structure
+ Added optional config reactivity. Defaults to false to preserve backwards compatibility as new behaviour may be surprising if implementation doesn't expect it
+ Added tests for new features
+ Updated docs
+ Added premove support (didn't realise it would just take 1 line lol)

I understand this is quite a big PR and I plan on continuing development so feel free to let me know if you'd rather I just fork the repo instead! 👍

Also very new to typescript and frontend stuff in general, so any and all feedback very much welcomed :)

---------------

# Planned changes: 
- Add events for: threefold repetition, insufficient material and game over (which returns which type of game over)
- Fix enpassent animation
- Fix promotion dialogue click through (if one of your own pieces is behind the selected promotion piece, it will be selected accidentally)
- Maybe split API into 2 classes? 1 for public exposed API functionality and 1 for private handling of board and game
- ~~Premove support~~ Edit: added! 
- Game history viewer
- Fix free move mode
- Maybe obscure config from user? ie. move entirely to props and emits for more idiomatic Vue component behaviour
- Possibly engine integration?

### CODE REVIEW

**Review by qwerty084 — APPROVED** [review]
Great work! Thank you.

**Comment by qwerty084** [comment]
I will include this pr in v1.2 release. I will release an alpha version soon, for testing. But we can try also include your other planned changes in it.

**Comment by qwerty084** [comment]
I've created a pre-release with your changes.

```sh
npm i vue3-chessboard@1.2.0-alpha.1
```

**Comment by gavin-lb** [comment]
Hi, thanks for including my changes. Sorry I've not made another PR with any of the planned changes yet, I was implementing the threefold repetition event and found a bug in chess.js, so I fixed it and [made a PR](https://github.com/jhlywa/chess.js/pull/417) and that kind of lead me down a chess.js rabbit hole making more changes. 

Once I've finished with some chess.js changes I'll be back to work on the above planned changes.

**Pull request merged**
